# Generated by Django 4.2.3 on 2023-10-03 19:15

import Todo_List_App.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0077_task_important_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=Todo_List_App.models.profile_picture_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 15, 15, 779556, tzinfo=datetime.timezone.utc)),
        ),
    ]
