# Generated by Django 4.2.3 on 2023-10-03 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_List_App', '0078_alter_profile_profile_picture_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 19, 15, 27, 217289, tzinfo=datetime.timezone.utc)),
        ),
    ]
